### ISSUE TITLE
Indent guide

### ISSUE THREAD

**Issue by armic** [braver/vscode-solarized#1]
Great theme - my favorite one on VSCode.  I was wondering if you could add the ability to enable indent guides?  Maybe the same color as comments?

**Comment by braver** [comment]
Indent guides are an editor setting and if you enable them you should be seeing subtle guides:

<img width="297" alt="screen shot 2017-03-03 at 11 10 36" src="https://cloud.githubusercontent.com/assets/2543659/23547093/26b919e4-0002-11e7-95cf-e847e78571d6.png">

**Comment by armic** [comment]
I see them in the solarized light scheme, but not the solarized dark one.

![image](https://cloud.githubusercontent.com/assets/14307368/23548460/a03dd868-ffd5-11e6-8932-fc6f434cf0e4.png)

![image](https://cloud.githubusercontent.com/assets/14307368/23548465/a4c40b00-ffd5-11e6-8d7a-8f640e6a662a.png)

EDIT: @braver Oh nevermind, I see that they're there, but they're very faint on the dark theme.  Might it be possible to make them a bit more noticeable?  Currently they're difficult to use practically.

**Comment by braver** [comment]
Oh, you're right! They're no use like this. Thanks for catching that.
