### ISSUE TITLE
Change color of explorer / side bar

### ISSUE THREAD

**Issue by andyleejordan** [braver/vscode-solarized#2]
Hello!

Have you been able to figure out how to change the dark grey color of the explorer and side bar? The "high contrast" theme definitely does it, but I can't find many themes that can. I _love_ Solarized, but the dark grey on the left is terrible clash with the rest of the theme.

**Comment by braver** [comment]
I don't think it's possible. The High-Contrast theme [seems to trigger stylesheet changes](https://github.com/Microsoft/vscode/search?utf8=✓&q=high+contrast) deep inside VS Code that regular themes can't reach.

Lots of discussion about it here in [this currently still open issue](https://github.com/Microsoft/vscode/issues/3112).

**Comment by andyleejordan** [comment]
Ah, thanks for the pointer! I'll follow that issue.

**Comment by shashankKeshava** [comment]
@andschwa you can change the Explorer / Side Bar font and colour by editing User Configurations. Follow [VSCode SideBar Theme Color Reference](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_side-bar) for Docs
