### ISSUE TITLE
Incorrect foreground text colour w/ workbench theme

### ISSUE THREAD

**Issue by tpict** [braver/vscode-solarized#9]
Using "Braver's Solarized Light"
![screenshot from 2018-06-22 15-27-01](https://user-images.githubusercontent.com/12588098/41781983-d21507c6-7630-11e8-9cb6-7395e1ded26e.png)

Using "Braver's Solarized Light (themed workbench)
![screenshot from 2018-06-22 15-27-35](https://user-images.githubusercontent.com/12588098/41781986-d2696fbe-7630-11e8-8bc5-03ffbd952cdd.png)

The text is too dark in the themed workbench version

**Comment by DavidRGriswold** [comment]
This will be fixed shortly. Sorry for the extremely long lag time on this!

**Comment by tpict** [comment]
thank you! :sparkles:
